Make the pre-commit hook stash unstaged changes.

diff --git a/hooks/git-pre-commit b/hooks/git-pre-commit
--- a/hooks/git-pre-commit
+++ b/hooks/git-pre-commit
@@ -8,6 +8,8 @@ die() {
 }
 
 cd "$(dirname "$(git rev-parse --git-dir)")"
+echo "Precommit: Stashing unstaged changes..."
+git stash save --keep-index --include-untracked "GoHS presubmit stash ($(date))."
 
 set +e
 
@@ -52,6 +54,14 @@ if test "$result" -ne 0; then
     die "$result"
 fi
 rm "$testLog"
+
+echo "Precommit: Popping stashed changes..."
+git stash pop
+result="$?"
+if test "$result" -ne 0; then
+    echo "Precommit: Failed to unstash changes prior to commit."
+    die "$result"
+fi
 
 echo "Precommit: Success."
 exit 0
